name: Invoke Bloodhound Lambda

on:
  schedule:
    # Run at 11 AM and 11 PM EST (4 PM and 4 AM UTC)
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # IMPORTANT:
        # This region must match the region used by Terraform
        # in infra/provider.tf where the Lambda is deployed.
        aws-region: us-west-2

    - name: Invoke Bloodhound Lambda function
        # IMPORTANT:
        # This region must match the Lambda deployment region.
      run: |
        echo '{}' > test_event.json
        aws lambda invoke --function-name BloodhoundLambdaV2 --cli-binary-format raw-in-base64-out --payload file://test_event.json output.txt --region us-west-2
        cat output.txt
